spring:
  datasource:
    url: jdbc:mysql://localhost:3306/np1
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 7 # 전역 배치 사이즈 설정